### ISSUE TITLE
New Tab group from all tabs skips tabs following tabs without source code

### ISSUE THREAD

**Issue by valerii-pohrebniak-rg** [jhhtaylor/tabstronaut#91]
When there are open few tabs and there is some tab without source code (like `settings` or `extensions`) and I try to use comand `New Tab Group from all tabs` - this extension create group, but skips all tabs following the `non source code tab`

For example I have 17 tabs opened and try this command - i have new created group only with two first tabs

![Снимок экрана_2024-04-12_15-20-48](https://github.com/jhhtaylor/tabstronaut/assets/125459646/891dafeb-639c-4e08-af5e-9069a1501be6)
![Снимок экрана_2024-04-12_15-19-35](https://github.com/jhhtaylor/tabstronaut/assets/125459646/f69d86f9-c1ca-4922-a1e5-dd4b478629e0)

**Comment by jhhtaylor** [comment]
Hi @valerii-pohrebniak-rg 
Thanks for using Tabstronaut!

This issue with source code files is a well-known issue with the VS Code API itself - it cannot detect and handle non-source code files. I could not figure out how to get around it. If you can figure out how to do it, by all means, you can make a PR and I can review it and implement it.

The issue is so well known I give the user a warning when making a new tab group 😅:
![image](https://github.com/jhhtaylor/tabstronaut/assets/29454433/0bb63369-f351-4111-b35c-c193fd693a85)

**Comment by valerii-pohrebniak-rg** [comment]
Thanks for answer, seems I'm blind, because didn`t see  that warning about non-source code files.
Thank you for your work!
